<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="PsYcHoDrOid" failures="1" tests="1" name="Test" time="0.084" errors="0" timestamp="2023-02-14T11:56:26 IST">
  <testcase classname="com.test.OrganisingTestCases" name="e" time="0.016">
    <failure type="java.lang.AssertionError" message="case failed expected [max1123] but found [Welcome max123]">
      <![CDATA[java.lang.AssertionError: case failed expected [max1123] but found [Welcome max123]
at com.test.OrganisingTestCases.e(OrganisingTestCases.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- e -->
  <testcase classname="com.test.OrganisingTestCases" name="b" time="0.0">
    <ignored/>
  </testcase> <!-- b -->
  <testcase classname="com.test.OrganisingTestCases" name="a" time="0.0">
    <ignored/>
  </testcase> <!-- a -->
  <testcase classname="com.test.OrganisingTestCases" name="d" time="0.0">
    <ignored/>
  </testcase> <!-- d -->
  <testcase classname="com.test.OrganisingTestCases" name="c" time="0.0">
    <ignored/>
  </testcase> <!-- c -->
</testsuite> <!-- Test -->
